name: deploy aws lambda

on: 
  push:
    branches: 
      - main    
    paths:
      - 'Lambda/**'

jobs: # defines the job to deploy the lambda function
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python # sets up python 3.12 environment
        uses: actions/setup-python@v4
        with:   
          python-version: '3.12'

      - name: Install dependencies # installs dependencies listed in requirements.txt
        run: |
         python -m pip install --upgrade pip
         pip install -r Lambda/requirements.txt

      - name: Configure AWS Credentials # configures aws credentials using secrets stored in github
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda # zips and deploys the lambda function
        run: |
         cd Lambda
         zip -r function.zip .
         aws lambda update-function-code --function-name MyTestCICDLabmda --zip-file fileb://function.zip
